### ISSUE TITLE
SQLがおかしい

### ISSUE THREAD

**Issue by yterajima** [gon-papa/gakureco#1]
https://github.com/gon-papa/gakureco/blob/bb5255c42755f78f1e835844f25e194d13e9b869/db/20210623234215-users.sql#L4

- `NOT NULL NOT NULL` になっている
- `PRIMARY KEY` を勘違いしているっぽい。
    https://www.postgresql.jp/document/9.4/html/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS

**Comment by gon-papa** [comment]
PRIMARY KEY はNOT NULLとUNIQUEの複合だったのですね・・・！
ドキュメントまで教えてもらえて、めちゃくちゃ助かります。
ありがとうございます！
